version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    environment:
      - MSSQL_SA_PASSWORD=sa@12345
      - ACCEPT_EULA=Y
    volumes:
      - C:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"

  webapi:
    build: .
    image: webapi
    ports:
      - "8081:80"
    depends_on:
      - db
